### ISSUE TITLE
microcontroller code

### ISSUE THREAD

**Issue by mohamadnikan2013** [JuustoMestari/GPSTracker#1]
Hey,
I want to design a system just like you did and I find out I need to program the AVR  microcontroller. I searched in your repo but I didn't find any AVR microcontroller code!!
would you please push AVR microcontroller code? especially that part of the code that the AVR micro write data on the sd card.
thank you

**Comment by JuustoMestari** [comment]
Hello,

The arduino code is available here : [GPS_v3.ino](../blob/master/Arduino/GPS_V3.ino)
or do you mean something else?

**Comment by mohamadnikan2013** [comment]
yes
AVR code 
for ATMEGA microprocessor

**Comment by JuustoMestari** [comment]
I basically used [Arduino](https://www.arduino.cc/en/main/software) to program the microcontroller. It's really popular and easier to use for me. 
The link I gave you in the previous message is a sketch that can be loaded in the Arduino IDE and then uploaded to the microcontroller.
